apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy
  labels:
    type: apache-ws
spec:
  selector:
    matchLabels:
        type: apache-ws
  template:
    metadata:
      labels:
        type: apache-ws
    spec:
      containers:
        - name: c01
          image: ubuntu/apache2
---
apiVersion: v1
kind: Service
metadata:
  name: apache-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30500
      port: 9000
      targetPort: 80
  selector:
    type: apache-ws
